[package]
name = "rs"
version = "0.1.0"
authors = ["Vanessa McHale <vanessa.mchale@iohk.io>"]
exclude = [ ".gitignore" ]

[profile.release]
lto = true
panic = "abort"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lev"
harness = false

[dependencies]
levenshtein = "1.0"
strsim = "0.9"
